### PR TITLE
Add releasers info for tito and brew

### PR DESCRIPTION
**Pull request by dymurray**
Also includes rename from sbcli->apb

### CODE REVIEW

**Comment by djwhatle** [comment]
Get an error when I try to build this.

[~/code/go/src/github.com/automationbroker/sbcli] derek $ >> go build
main.go:20:2: cannot find package "github.com/automationbroker/apb/cmd" in any of:
	/Users/derek/code/go/src/github.com/automationbroker/sbcli/vendor/github.com/automationbroker/apb/cmd (vendor tree)
	/usr/local/Cellar/go/1.10.2/libexec/src/github.com/automationbroker/apb/cmd (from $GOROOT)
	/Users/derek/code/go/src/github.com/automationbroker/apb/cmd (from $GOPATH)
[~/code/go/src/github.com/automationbroker/sbcli] derek $ >>

**Comment by djwhatle** [comment]
VISACK, built locally for me after renaming my src dir from `sbcli` to `apb`

**Comment by jmrodri** [comment]
I was able to do a clean build locally:

```

Successfully built: /tmp/tito/apb-1.9.1-1.git.59.8ae8f89.fc28.src.rpm
        - /tmp/tito/x86_64/apb-1.9.1-1.git.59.8ae8f89.fc28.x86_64.rpm
        - /tmp/tito/noarch/apb-devel-1.9.1-1.git.59.8ae8f89.fc28.noarch.rpm
```

I installed the python version, then install the new go version. It worked. All of the python files were removed and replaced by the new go executable.

#### Python files gone
```
[jesusr@speed3 ansible-playbook-bundle{master}]$  rpm -qlp /tmp/tito/noarch/apb-1.3.0-1.git.3.c13452d.fc28.noarch.rpm
/usr/bin/apb
/usr/lib/python2.7/site-packages/apb
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/PKG-INFO
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/SOURCES.txt
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/dependency_links.txt
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/entry_points.txt
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/requires.txt
/usr/lib/python2.7/site-packages/apb-1.2.12-py2.7.egg-info/top_level.txt
/usr/lib/python2.7/site-packages/apb/__init__.py
/usr/lib/python2.7/site-packages/apb/__init__.pyc
/usr/lib/python2.7/site-packages/apb/__init__.pyo
/usr/lib/python2.7/site-packages/apb/cli.py
/usr/lib/python2.7/site-packages/apb/cli.pyc
/usr/lib/python2.7/site-packages/apb/cli.pyo
/usr/lib/python2.7/site-packages/apb/dat
/usr/lib/python2.7/site-packages/apb/dat/Dockerfile.j2
/usr/lib/python2.7/site-packages/apb/dat/Makefile.j2
/usr/lib/python2.7/site-packages/apb/dat/apb.yml.j2
/usr/lib/python2.7/site-packages/apb/dat/playbooks
/usr/lib/python2.7/site-packages/apb/dat/playbooks/playbook.yml.j2
/usr/lib/python2.7/site-packages/apb/dat/roles
/usr/lib/python2.7/site-packages/apb/dat/roles/bind
/usr/lib/python2.7/site-packages/apb/dat/roles/bind/tasks
/usr/lib/python2.7/site-packages/apb/dat/roles/bind/tasks/main.yml.j2
/usr/lib/python2.7/site-packages/apb/dat/roles/deprovision
/usr/lib/python2.7/site-packages/apb/dat/roles/deprovision/tasks
/usr/lib/python2.7/site-packages/apb/dat/roles/deprovision/tasks/main.yml.j2
/usr/lib/python2.7/site-packages/apb/dat/roles/provision
/usr/lib/python2.7/site-packages/apb/dat/roles/provision/tasks
/usr/lib/python2.7/site-packages/apb/dat/roles/provision/tasks/main.yml.j2
/usr/lib/python2.7/site-packages/apb/dat/roles/unbind
/usr/lib/python2.7/site-packages/apb/dat/roles/unbind/tasks
/usr/lib/python2.7/site-packages/apb/dat/roles/unbind/tasks/main.yml.j2
/usr/lib/python2.7/site-packages/apb/engine.py
/usr/lib/python2.7/site-packages/apb/engine.pyc
/usr/lib/python2.7/site-packages/apb/engine.pyo
/usr/share/man/man1/apb.1.gz
[jesusr@speed3 ansible-playbook-bundle{master}]$ ls /usr/share/man/man1/apb*
ls: cannot access '/usr/share/man/man1/apb*': No such file or directory
[jesusr@speed3 ansible-playbook-bundle{master}]$ ls /usr/lib/python2.7/site-packages/apb
ls: cannot access '/usr/lib/python2.7/site-packages/apb': No such file or directory
```

Go one is now installed:
```
[jesusr@speed3 apb{dymurray-apb}]$ apb
ServiceBundles are images that represent lifecycle components
in that they contain all of the orchestration logic to manage
an application through out it's lifecycle, i.e. install, uninstall,
bind, unbind, etc.  ServiceBundles are intended to be invoked and run
as a short job to execute the intended work, example I want to deploy a
postgres database to my kubernetes cluster.

Usage:
  apb [command]

Available Commands:
  binding     Manage bindings
  broker      Interact with an Automation Broker instance
  bundle      Interact with ServiceBundles
  completion  Generates shell completion scripts.
  help        Help about any command
  registry    Configure registry adapters

Flags:
      --config string   configuration file (default is $HOME/.apb)
  -h, --help            help for apb
  -v, --verbose         verbose output

Use "apb [command] --help" for more information about a command.
```

**Comment by djwhatle** [comment]
@dymurray one last thing, need to change the .gitignore entry for the `sbcli` binary to `apb`.

**Pull request merged**
